# Generated by Django 4.0.3 on 2022-04-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collegeplayers_defense_drafthistory_offense_roster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='defensiveIntereptions',
            new_name='defensiveInterceptions',
        ),
    ]
