# Generated by Django 4.0.3 on 2022-04-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_defensiveintereptions_teams_defensiveinterceptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defense',
            old_name='safteys',
            new_name='safeties',
        ),
        migrations.RenameField(
            model_name='specialteams',
            old_name='ALlFMG',
            new_name='AllFMG',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='loses',
            new_name='losses',
        ),
    ]
