# Generated by Django 4.0.3 on 2022-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_safteys_defense_safeties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='height',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
