# Generated by Django 4.0.3 on 2022-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_defense_assistedtackles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offense',
            old_name='yardsFromScrimage',
            new_name='yardsFromScrimmage',
        ),
    ]
