# Generated by Django 4.0.3 on 2022-04-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_offense_attempts_alter_offense_catchpercentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialteams',
            old_name='AllFMG',
            new_name='AllFGM',
        ),
        migrations.RenameField(
            model_name='specialteams',
            old_name='fiftyPlusFMG',
            new_name='fiftyPlusFGM',
        ),
    ]
