# Generated by Django 4.0.3 on 2022-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_allfmg_specialteams_allfgm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='birthDate',
            field=models.CharField(max_length=12),
        ),
    ]
