# Generated by Django 4.0.3 on 2022-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_roster_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='rosterID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
