# Generated by Django 4.0.3 on 2022-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_roster_rosterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='allowedSacks',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='defensiveSacks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='sackPercentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='yardsAgainst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
