# Generated by Django 4.0.3 on 2022-04-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_drafted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeplayers',
            old_name='playerid',
            new_name='playeid',
        ),
    ]
