# Generated by Django 4.0.3 on 2022-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_playerid_collegeplayers_playeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeplayers',
            old_name='playeid',
            new_name='playerid',
        ),
    ]
