# Generated by Django 4.0.3 on 2022-04-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_playeid_collegeplayers_playerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drafted',
            fields=[
                ('playerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('position', models.CharField(max_length=5)),
                ('athleteGrade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('positionGrade', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('team', models.CharField(max_length=3)),
                ('drafted', models.BooleanField(default=False)),
            ],
        ),
    ]
