# Generated by Django 4.0.3 on 2022-04-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_drafted'),
    ]

    operations = [
        migrations.AddField(
            model_name='drafted',
            name='pick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drafted',
            name='drafted',
            field=models.BooleanField(),
        ),
    ]
